version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: middleware-api-mongodb-development
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/development:/data/db
networks:
  default:
    name: middleware-api-mongodb-development-network