version: '3.1'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb/development:/data/db
  middleware-api:
    build:
      context: .
    environment:
      MONGODB_URI: mongodb://mongo:27017/db
    ports:
      - 4000:4000
