version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: middleware-api-mongodb-test
    ports:
      - 27018:27017
networks:
  default:
    name: middleware-api-mongodb-test-network